### ISSUE TITLE
Take ownership as primary maintainer

### ISSUE THREAD

**Issue by MasterEric** [MasterEric/polymod#1]
See the discussion in larsiusprime/polymod#51

This involves:

- [ ] Cleaning up the repository to use proper GitFlow
- [ ] Migrate over all issues
- [ ] Migrate over all pull requests
- [ ] Advertising the repository as the primary repository

**Comment by prokube** [comment]
congartulations dude

![image](https://user-images.githubusercontent.com/68293280/138140738-fc266371-dc20-4736-8b8c-0596cdafc702.png)

**Comment by MasterEric** [comment]
Done.
