### ISSUE TITLE
Polymod's issue

### ISSUE THREAD

**Issue by Cheemsandfriends** [MasterEric/polymod#18]
The main issue I have with polymod is that it doesn't load the mods anymore.

It always gives a null because it doesn't load. I can work with the game but It's kinda shitty that it gives a null always. even though I'm trying to load one

**Comment by MasterEric** [comment]
Hey, sorry I didn't see this.

Polymod will return null if it experiences an error during mod loading. Set this parameter to preview these errors and determine how to proceed:

`errorCallback:PolymodError->Void`

If you are working specifically with Friday Night Funkin', that requires setting up a list of paths to use for the different asset libraries.

**Comment by Cheemsandfriends** [comment]
Oh, Hi again @MasterEric! 
So I thought there wasn't much of a solution so I downgraded polymod to back before the Funkinfixes.
And pretty much I worked there. But I guess that I have tested again, It doesn't work anymore on haxe 4.2.4
Idk, it gives me a null access and crashes.
Do you know what might do that?

**Comment by MasterEric** [comment]
Knowing there's a null access error doesn't provide me with enough information to help you.

If you can point out the exact line where the error occurs, that would be useful.

If you're using VSCode, go to [this guide](https://gamebanana.com/tuts/13798) and follow the section 1.13: Troubleshooting. This will show you how to run a Haxe program with Debug support; if you run the application this way, the program will give VSCode the information necessary to highlight the exact line that contains the error.

**Comment by Cheemsandfriends** [comment]
> Knowing there's a null access error doesn't provide me with enough information to help you.
> 
> If you can point out the exact line where the error occurs, that would be useful.
> 
> If you're using VSCode, go to [this guide](https://gamebanana.com/tuts/13798) and follow the section 1.13: Troubleshooting. This will show you how to run a Haxe program with Debug support; if you run the application this way, the program will give VSCode the information necessary to highlight the exact line that contains the error.

Oh, do you mean like the calls of that? I can show the Windows Terminal with the error If you want

**Comment by MasterEric** [comment]
Hey @Cheemsandfriends if you are still having issues, please update the library using `haxelib install polymod` and if you still have issues, create a new discussion on https://github.com/larsiusprime/polymod (I am now a maintainer there so I can help you out if needed)
